package com.sts.blue.app_m.mybatis_generator.entity;

public class AccountRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role.role_status
     *
     * @mbggenerated
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role.role_remark
     *
     * @mbggenerated
     */
    private String roleRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role.role_permission_id
     *
     * @mbggenerated
     */
    private Integer rolePermissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role.role_id
     *
     * @return the value of account_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role.role_id
     *
     * @param roleId the value for account_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role.role_name
     *
     * @return the value of account_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role.role_name
     *
     * @param roleName the value for account_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role.role_status
     *
     * @return the value of account_role.role_status
     *
     * @mbggenerated
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role.role_status
     *
     * @param roleStatus the value for account_role.role_status
     *
     * @mbggenerated
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role.role_remark
     *
     * @return the value of account_role.role_remark
     *
     * @mbggenerated
     */
    public String getRoleRemark() {
        return roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role.role_remark
     *
     * @param roleRemark the value for account_role.role_remark
     *
     * @mbggenerated
     */
    public void setRoleRemark(String roleRemark) {
        this.roleRemark = roleRemark == null ? null : roleRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role.role_permission_id
     *
     * @return the value of account_role.role_permission_id
     *
     * @mbggenerated
     */
    public Integer getRolePermissionId() {
        return rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role.role_permission_id
     *
     * @param rolePermissionId the value for account_role.role_permission_id
     *
     * @mbggenerated
     */
    public void setRolePermissionId(Integer rolePermissionId) {
        this.rolePermissionId = rolePermissionId;
    }
}