package com.sts.blue.app_m.mybatis_generator.dao;

import com.sts.blue.app_m.mybatis_generator.entity.AccountPermission;
import org.springframework.stereotype.Repository;

@Repository
public interface AccountPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_permission
     *
     * @mbggenerated
     */
    int insert(AccountPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_permission
     *
     * @mbggenerated
     */
    int insertSelective(AccountPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_permission
     *
     * @mbggenerated
     */
    AccountPermission selectByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountPermission record);
}