package com.sts.blue.app_m.mybatis_generator.dao;

import com.sts.blue.app_m.mybatis_generator.entity.AccountRole;
import org.springframework.stereotype.Repository;

@Repository
public interface AccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbggenerated
     */
    int insert(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbggenerated
     */
    int insertSelective(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbggenerated
     */
    AccountRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountRole record);
}