package com.sts.blue.app_m.mybatis_generator.entity;

import java.util.Date;

public class AccountUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_age
     *
     * @mbggenerated
     */
    private Integer userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_sex
     *
     * @mbggenerated
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_mail
     *
     * @mbggenerated
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_entry_time
     *
     * @mbggenerated
     */
    private Date userEntryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_idcard_type
     *
     * @mbggenerated
     */
    private Integer userIdcardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_idcard_num
     *
     * @mbggenerated
     */
    private String userIdcardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_industry
     *
     * @mbggenerated
     */
    private String userIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_position
     *
     * @mbggenerated
     */
    private String userPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_head_ico
     *
     * @mbggenerated
     */
    private String userHeadIco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_role
     *
     * @mbggenerated
     */
    private Integer userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_remark
     *
     * @mbggenerated
     */
    private String userRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_id
     *
     * @return the value of account_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_id
     *
     * @param userId the value for account_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_name
     *
     * @return the value of account_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_name
     *
     * @param userName the value for account_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_age
     *
     * @return the value of account_user.user_age
     *
     * @mbggenerated
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_age
     *
     * @param userAge the value for account_user.user_age
     *
     * @mbggenerated
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_sex
     *
     * @return the value of account_user.user_sex
     *
     * @mbggenerated
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_sex
     *
     * @param userSex the value for account_user.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_phone
     *
     * @return the value of account_user.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_phone
     *
     * @param userPhone the value for account_user.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_mail
     *
     * @return the value of account_user.user_mail
     *
     * @mbggenerated
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_mail
     *
     * @param userMail the value for account_user.user_mail
     *
     * @mbggenerated
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_entry_time
     *
     * @return the value of account_user.user_entry_time
     *
     * @mbggenerated
     */
    public Date getUserEntryTime() {
        return userEntryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_entry_time
     *
     * @param userEntryTime the value for account_user.user_entry_time
     *
     * @mbggenerated
     */
    public void setUserEntryTime(Date userEntryTime) {
        this.userEntryTime = userEntryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_idcard_type
     *
     * @return the value of account_user.user_idcard_type
     *
     * @mbggenerated
     */
    public Integer getUserIdcardType() {
        return userIdcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_idcard_type
     *
     * @param userIdcardType the value for account_user.user_idcard_type
     *
     * @mbggenerated
     */
    public void setUserIdcardType(Integer userIdcardType) {
        this.userIdcardType = userIdcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_idcard_num
     *
     * @return the value of account_user.user_idcard_num
     *
     * @mbggenerated
     */
    public String getUserIdcardNum() {
        return userIdcardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_idcard_num
     *
     * @param userIdcardNum the value for account_user.user_idcard_num
     *
     * @mbggenerated
     */
    public void setUserIdcardNum(String userIdcardNum) {
        this.userIdcardNum = userIdcardNum == null ? null : userIdcardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_industry
     *
     * @return the value of account_user.user_industry
     *
     * @mbggenerated
     */
    public String getUserIndustry() {
        return userIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_industry
     *
     * @param userIndustry the value for account_user.user_industry
     *
     * @mbggenerated
     */
    public void setUserIndustry(String userIndustry) {
        this.userIndustry = userIndustry == null ? null : userIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_position
     *
     * @return the value of account_user.user_position
     *
     * @mbggenerated
     */
    public String getUserPosition() {
        return userPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_position
     *
     * @param userPosition the value for account_user.user_position
     *
     * @mbggenerated
     */
    public void setUserPosition(String userPosition) {
        this.userPosition = userPosition == null ? null : userPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_head_ico
     *
     * @return the value of account_user.user_head_ico
     *
     * @mbggenerated
     */
    public String getUserHeadIco() {
        return userHeadIco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_head_ico
     *
     * @param userHeadIco the value for account_user.user_head_ico
     *
     * @mbggenerated
     */
    public void setUserHeadIco(String userHeadIco) {
        this.userHeadIco = userHeadIco == null ? null : userHeadIco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_role
     *
     * @return the value of account_user.user_role
     *
     * @mbggenerated
     */
    public Integer getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_role
     *
     * @param userRole the value for account_user.user_role
     *
     * @mbggenerated
     */
    public void setUserRole(Integer userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_remark
     *
     * @return the value of account_user.user_remark
     *
     * @mbggenerated
     */
    public String getUserRemark() {
        return userRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_remark
     *
     * @param userRemark the value for account_user.user_remark
     *
     * @mbggenerated
     */
    public void setUserRemark(String userRemark) {
        this.userRemark = userRemark == null ? null : userRemark.trim();
    }
}