package com.sts.blue.app_m.mybatis_generator.entity;

public class AccountPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_id
     *
     * @mbggenerated
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_main_menu
     *
     * @mbggenerated
     */
    private String permissionMainMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_mine_client
     *
     * @mbggenerated
     */
    private String permissionMineClient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_mine_zhiweidan
     *
     * @mbggenerated
     */
    private String permissionMineZhiweidan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_mine_jiekuandan
     *
     * @mbggenerated
     */
    private String permissionMineJiekuandan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_business_shenpi
     *
     * @mbggenerated
     */
    private String permissionBusinessShenpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_business_zhishiku
     *
     * @mbggenerated
     */
    private String permissionBusinessZhishiku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_business_rencaiku
     *
     * @mbggenerated
     */
    private String permissionBusinessRencaiku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_business_client_manager
     *
     * @mbggenerated
     */
    private String permissionBusinessClientManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_business_zuodanguanli
     *
     * @mbggenerated
     */
    private String permissionBusinessZuodanguanli;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_business_shujutongji
     *
     * @mbggenerated
     */
    private String permissionBusinessShujutongji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_business_caiwuguanli
     *
     * @mbggenerated
     */
    private String permissionBusinessCaiwuguanli;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_system_renyuanguanli
     *
     * @mbggenerated
     */
    private String permissionSystemRenyuanguanli;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_permission.permission_system_shujuzidian
     *
     * @mbggenerated
     */
    private String permissionSystemShujuzidian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_id
     *
     * @return the value of account_permission.permission_id
     *
     * @mbggenerated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_id
     *
     * @param permissionId the value for account_permission.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_main_menu
     *
     * @return the value of account_permission.permission_main_menu
     *
     * @mbggenerated
     */
    public String getPermissionMainMenu() {
        return permissionMainMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_main_menu
     *
     * @param permissionMainMenu the value for account_permission.permission_main_menu
     *
     * @mbggenerated
     */
    public void setPermissionMainMenu(String permissionMainMenu) {
        this.permissionMainMenu = permissionMainMenu == null ? null : permissionMainMenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_mine_client
     *
     * @return the value of account_permission.permission_mine_client
     *
     * @mbggenerated
     */
    public String getPermissionMineClient() {
        return permissionMineClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_mine_client
     *
     * @param permissionMineClient the value for account_permission.permission_mine_client
     *
     * @mbggenerated
     */
    public void setPermissionMineClient(String permissionMineClient) {
        this.permissionMineClient = permissionMineClient == null ? null : permissionMineClient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_mine_zhiweidan
     *
     * @return the value of account_permission.permission_mine_zhiweidan
     *
     * @mbggenerated
     */
    public String getPermissionMineZhiweidan() {
        return permissionMineZhiweidan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_mine_zhiweidan
     *
     * @param permissionMineZhiweidan the value for account_permission.permission_mine_zhiweidan
     *
     * @mbggenerated
     */
    public void setPermissionMineZhiweidan(String permissionMineZhiweidan) {
        this.permissionMineZhiweidan = permissionMineZhiweidan == null ? null : permissionMineZhiweidan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_mine_jiekuandan
     *
     * @return the value of account_permission.permission_mine_jiekuandan
     *
     * @mbggenerated
     */
    public String getPermissionMineJiekuandan() {
        return permissionMineJiekuandan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_mine_jiekuandan
     *
     * @param permissionMineJiekuandan the value for account_permission.permission_mine_jiekuandan
     *
     * @mbggenerated
     */
    public void setPermissionMineJiekuandan(String permissionMineJiekuandan) {
        this.permissionMineJiekuandan = permissionMineJiekuandan == null ? null : permissionMineJiekuandan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_business_shenpi
     *
     * @return the value of account_permission.permission_business_shenpi
     *
     * @mbggenerated
     */
    public String getPermissionBusinessShenpi() {
        return permissionBusinessShenpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_business_shenpi
     *
     * @param permissionBusinessShenpi the value for account_permission.permission_business_shenpi
     *
     * @mbggenerated
     */
    public void setPermissionBusinessShenpi(String permissionBusinessShenpi) {
        this.permissionBusinessShenpi = permissionBusinessShenpi == null ? null : permissionBusinessShenpi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_business_zhishiku
     *
     * @return the value of account_permission.permission_business_zhishiku
     *
     * @mbggenerated
     */
    public String getPermissionBusinessZhishiku() {
        return permissionBusinessZhishiku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_business_zhishiku
     *
     * @param permissionBusinessZhishiku the value for account_permission.permission_business_zhishiku
     *
     * @mbggenerated
     */
    public void setPermissionBusinessZhishiku(String permissionBusinessZhishiku) {
        this.permissionBusinessZhishiku = permissionBusinessZhishiku == null ? null : permissionBusinessZhishiku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_business_rencaiku
     *
     * @return the value of account_permission.permission_business_rencaiku
     *
     * @mbggenerated
     */
    public String getPermissionBusinessRencaiku() {
        return permissionBusinessRencaiku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_business_rencaiku
     *
     * @param permissionBusinessRencaiku the value for account_permission.permission_business_rencaiku
     *
     * @mbggenerated
     */
    public void setPermissionBusinessRencaiku(String permissionBusinessRencaiku) {
        this.permissionBusinessRencaiku = permissionBusinessRencaiku == null ? null : permissionBusinessRencaiku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_business_client_manager
     *
     * @return the value of account_permission.permission_business_client_manager
     *
     * @mbggenerated
     */
    public String getPermissionBusinessClientManager() {
        return permissionBusinessClientManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_business_client_manager
     *
     * @param permissionBusinessClientManager the value for account_permission.permission_business_client_manager
     *
     * @mbggenerated
     */
    public void setPermissionBusinessClientManager(String permissionBusinessClientManager) {
        this.permissionBusinessClientManager = permissionBusinessClientManager == null ? null : permissionBusinessClientManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_business_zuodanguanli
     *
     * @return the value of account_permission.permission_business_zuodanguanli
     *
     * @mbggenerated
     */
    public String getPermissionBusinessZuodanguanli() {
        return permissionBusinessZuodanguanli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_business_zuodanguanli
     *
     * @param permissionBusinessZuodanguanli the value for account_permission.permission_business_zuodanguanli
     *
     * @mbggenerated
     */
    public void setPermissionBusinessZuodanguanli(String permissionBusinessZuodanguanli) {
        this.permissionBusinessZuodanguanli = permissionBusinessZuodanguanli == null ? null : permissionBusinessZuodanguanli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_business_shujutongji
     *
     * @return the value of account_permission.permission_business_shujutongji
     *
     * @mbggenerated
     */
    public String getPermissionBusinessShujutongji() {
        return permissionBusinessShujutongji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_business_shujutongji
     *
     * @param permissionBusinessShujutongji the value for account_permission.permission_business_shujutongji
     *
     * @mbggenerated
     */
    public void setPermissionBusinessShujutongji(String permissionBusinessShujutongji) {
        this.permissionBusinessShujutongji = permissionBusinessShujutongji == null ? null : permissionBusinessShujutongji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_business_caiwuguanli
     *
     * @return the value of account_permission.permission_business_caiwuguanli
     *
     * @mbggenerated
     */
    public String getPermissionBusinessCaiwuguanli() {
        return permissionBusinessCaiwuguanli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_business_caiwuguanli
     *
     * @param permissionBusinessCaiwuguanli the value for account_permission.permission_business_caiwuguanli
     *
     * @mbggenerated
     */
    public void setPermissionBusinessCaiwuguanli(String permissionBusinessCaiwuguanli) {
        this.permissionBusinessCaiwuguanli = permissionBusinessCaiwuguanli == null ? null : permissionBusinessCaiwuguanli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_system_renyuanguanli
     *
     * @return the value of account_permission.permission_system_renyuanguanli
     *
     * @mbggenerated
     */
    public String getPermissionSystemRenyuanguanli() {
        return permissionSystemRenyuanguanli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_system_renyuanguanli
     *
     * @param permissionSystemRenyuanguanli the value for account_permission.permission_system_renyuanguanli
     *
     * @mbggenerated
     */
    public void setPermissionSystemRenyuanguanli(String permissionSystemRenyuanguanli) {
        this.permissionSystemRenyuanguanli = permissionSystemRenyuanguanli == null ? null : permissionSystemRenyuanguanli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_permission.permission_system_shujuzidian
     *
     * @return the value of account_permission.permission_system_shujuzidian
     *
     * @mbggenerated
     */
    public String getPermissionSystemShujuzidian() {
        return permissionSystemShujuzidian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_permission.permission_system_shujuzidian
     *
     * @param permissionSystemShujuzidian the value for account_permission.permission_system_shujuzidian
     *
     * @mbggenerated
     */
    public void setPermissionSystemShujuzidian(String permissionSystemShujuzidian) {
        this.permissionSystemShujuzidian = permissionSystemShujuzidian == null ? null : permissionSystemShujuzidian.trim();
    }
}